export const categoriesToComeFirst = [
  "World Cup",
  "World Cup Qualifying",
  "Premier League",
  "UEFA Champions League",
  "UEFA Nations League",
  "European Championship",
  "European Championship Qualifying",
  "Sky Bet Championship",
  "UEFA Europa League",
  "UEFA Europa Conference League",
  "FA Cup",
  "EFL Cup",
  "International Friendlies",
  "Spanish Copa del Rey",
  "La Liga",
  "Spanish La Liga",
  "Ligue 1",
  "French Coupe de France",
  "French Ligue 1",
  "Italian Serie A",
  "German Bundesliga",
  "Danish Superliga",
  "League One",
  "League Two",
  "Championship",
  "Scottish Premiership",
  "Scottish Championship",
];