export const categoriesToComeFirst = [
  "World Cup",
  "World Cup Qualifying",
  "Premier League",
  "UEFA Champions League",
  "UEFA Nations League",
  "European Championship",
  "European Championship Qualifying",
  "International Friendlies",
  "Sky Bet Championship",
  "Europa League",
  "FA Cup",
  "EFL Cup",
  "Spanish Copa del Rey",
  "Conference League",
  "La Liga",
  "Spanish La Liga",
  "Ligue 1",
  "French Coupe de France",
  "French Ligue 1",
  "Italian Serie A",
  "German Bundesliga",
  "Danish Superliga",
  "League One",
  "League Two",
  "Championship",
  "Scottish Premiership",
  "Scottish Championship",
];